# Generated by Django 3.2.7 on 2022-01-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialisation', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phno', models.CharField(max_length=150)),
                ('fees', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=150)),
                ('diseases', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('medicine1', models.CharField(max_length=150)),
                ('medicine2', models.CharField(max_length=150)),
                ('labtest', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('hname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='vediocall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=150)),
                ('vedio', models.CharField(max_length=150)),
                ('did', models.CharField(max_length=150)),
            ],
        ),
    ]
